# Importing Libraries

In [ ]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords
import pandas as pd

In [ ]:
!pip install jupyter-dash

In [ ]:
!pip install sodapy

# Loading dataset

In [17]:
df=pd.read_csv("2021_Cities_Water_Security_Risks.csv")
print("Dimension of data frame:", df.shape)
df.head(20)

Dimension of data frame: (2349, 15)


Questionnaire Name  Account Number                   Account Name  \
0         Cities 2021            1093            City of Atlanta, GA   
1         Cities 2021            1093            City of Atlanta, GA   
2         Cities 2021            1184             City of Austin, TX   
3         Cities 2021            1499        Ajuntament de Barcelona   
4         Cities 2021            1499        Ajuntament de Barcelona   
5         Cities 2021            1499        Ajuntament de Barcelona   
6         Cities 2021            1499        Ajuntament de Barcelona   
7         Cities 2021            1499        Ajuntament de Barcelona   
8         Cities 2021            1499        Ajuntament de Barcelona   
9         Cities 2021            1499        Ajuntament de Barcelona   
10        Cities 2021            1499        Ajuntament de Barcelona   
11        Cities 2021            1499        Ajuntament de Barcelona   
12        Cities 2021            1850        Birmingham City Council   
13        Cities 2021            2185           Bristol City Council   
14        Cities 2021            2430         City of Burlington, VT   
15        Cities 2021            2621  Cambridgeshire County Council   
16        Cities 2021            3203            City of Chicago, IL   
17        Cities 2021            3417              New York City, NY   
18        Cities 2021            3422       Greater London Authority   
19        Cities 2021            3422       Greater London Authority   

                                              Country     CDP Region  \
0                            United States of America  North America   
1                            United States of America  North America   
2                            United States of America  North America   
3                                               Spain         Europe   
4                                               Spain         Europe   
5                                               Spain         Europe   
6                                               Spain         Europe   
7                                               Spain         Europe   
8                                               Spain         Europe   
9                                               Spain         Europe   
10                                              Spain         Europe   
11                                              Spain         Europe   
12  United Kingdom of Great Britain and Northern I...         Europe   
13  United Kingdom of Great Britain and Northern I...         Europe   
14                           United States of America  North America   
15  United Kingdom of Great Britain and Northern I...         Europe   
16                           United States of America  North America   
17                           United States of America  North America   
18  United Kingdom of Great Britain and Northern I...         Europe   
19  United Kingdom of Great Britain and Northern I...         Europe   

         ParentSection       Section Question Number  \
0   14. Water Security  Water Supply           14.2a   
1   14. Water Security  Water Supply           14.2a   
2   14. Water Security  Water Supply           14.2a   
3   14. Water Security  Water Supply           14.2a   
4   14. Water Security  Water Supply           14.2a   
5   14. Water Security  Water Supply           14.2a   
6   14. Water Security  Water Supply           14.2a   
7   14. Water Security  Water Supply           14.2a   
8   14. Water Security  Water Supply           14.2a   
9   14. Water Security  Water Supply           14.2a   
10  14. Water Security  Water Supply           14.2a   
11  14. Water Security  Water Supply           14.2a   
12  14. Water Security  Water Supply           14.2a   
13  14. Water Security  Water Supply           14.2a   
14  14. Water Security  Water Supply           14.2a   
15  14. Water Security  Water Supply           14.2a   
16  14. Water Security  W

# Data Exploration

## 1. Variable Section

In [24]:
df['Questionnaire Name'].unique()

array(['Cities 2021'], dtype=object)

In [25]:
df['Account Number'].unique()

array([  1093,   1184,   1499, ..., 863478, 863498, 863533], dtype=int64)

In [26]:
df['Account Name'].unique()

array(['City of Atlanta, GA', 'City of Austin, TX',
       'Ajuntament de Barcelona', ..., 'Coatzacoalcos', 'Zinacantepec',
       'San Antonio'], dtype=object)

In [28]:
df['CDP Region'].unique()

array(['North America', 'Europe', 'Southeast Asia and Oceania',
       'East Asia', 'Africa', 'Latin America', 'South and West Asia',
       'Middle East'], dtype=object)

In [27]:
df['Country'].unique()

array(['United States of America', 'Spain',
       'United Kingdom of Great Britain and Northern Ireland', 'Sweden',
       'Finland', 'Norway', 'Portugal', 'Canada', 'Denmark', 'Australia',
       'Italy', 'Japan', 'Taiwan, Greater China', 'South Africa',
       'Ethiopia', 'Netherlands', 'Greece', 'Thailand', 'Switzerland',
       'Germany', 'Colombia', 'Argentina', 'Brazil', 'India', 'Viet Nam',
       'Turkey', 'Indonesia', 'Nigeria', 'Pakistan',
       'China, Hong Kong Special Administrative Region', 'Peru', 'Mexico',
       'Russian Federation', 'France', 'Chile', 'Poland',
       'Republic of Korea', 'Israel', 'United Republic of Tanzania',
       'Morocco', 'Kenya', 'Singapore',
       'Democratic Republic of the Congo', "Côte d'Ivoire", 'Senegal',
       'Ghana', 'Ecuador', 'Madagascar', 'Latvia', 'Uruguay', 'Bulgaria',
       'Slovenia', 'Croatia', 'New Zealand', 'United Arab Emirates',
       'Paraguay', 'Uganda', 'Zambia', 'Zimbabwe', 'Sierra Leone',
       'Georgia', 'Hon

In [29]:
df['ParentSection'].unique()

array(['14. Water Security'], dtype=object)

In [30]:
df['Section'].unique()

array(['Water Supply'], dtype=object)

In [31]:
df['Question Number'].unique()

array(['14.2a'], dtype=object)

In [32]:
df['Question Name'].unique()

array(['Please identify the risks to your city’s water security as well as the timescale and level of risk.'],
      dtype=object)

In [33]:
df['Row Number'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,   0,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160], dtype=int64)

In [34]:
df['Water security risk drivers'].unique()

array(['Increased water stress', 'Higher water prices',
       'Declining water quality', 'Severe weather events',
       'Increased water scarcity', 'Increased water demand', 'Drought',
       'Question not applicable',
       'Inadequate or ageing water supply infrastructure',
       'Environmental regulations', 'Pollution incidents',
       'Energy supply issues', nan, 'Change in land-use',
       'Ecosystem vulnerability',
       'Other, please specify: Unsustainable abstraction',
       'Other, please specify: Climate change',
       'Rationing of municipal water supply',
       'Increased levels of plastic in freshwater bodies',
       'Water infestation/disease',
       'Unauthorised/unregistered water connections',
       'Other, please specify: flooding',
       'Other, please specify: Terrorist attack',
       'Other, please specify: teror',
       'Other, please specify: Earthquake/Tsunami',
       'Other, please specify: war', 'Other, please specify: pandemic',
       'Othe

In [35]:
df['Anticipated timescale'].unique()

array(['Short-term (by 2025)', 'Current', 'Medium-term (by 2050)',
       'Question not applicable', 'Long-term (after 2050)', nan],
      dtype=object)

In [36]:
df['Estimated magnitude of potential impact'].unique()

array(['Serious', 'Extremely serious', 'Less Serious',
       'Question not applicable', nan], dtype=object)

In [37]:
df['Estimated probability of impact'].unique()

array([nan, 'High', 'Medium-high', 'Medium', 'Medium-low',
       'Question not applicable', 'Low', 'Do not know'], dtype=object)

In [38]:
df['Risk description'].unique()

array(['The city depends on one river for water supply - the river has suffered from extreme droughts in previous years. Intensive rain fall has produced floods in the city affecting transportation, houses, and businesses',
       'The water cost burden is felt across all ZIP codes and but most seriously affects low-income residents and communities where they are located.',
       'Central Texas is drought prone and we depend on surface water for 100% of our supply.  Recently lake levels fell to 30% of full in 2012 before receiving drought breaking rains',
       ...,
       "Les nappes phréatiques permettent de compter sur des réserves d'eau pour quelques mois, mais si le stress hydrique augmente trop, elles pourraient s'épuiser rapidement.",
       'Los mantos freáticos, debido a la extracción mediante pozos, se están agotando y, a la vez, se tiene que realizar perforaciones muy profundas con agua con alta probabilidad de contaminantes',
       'Perdidad de zonas de recarga'], dtype=

Due to having only one value in these variable so we delete these variables:
- Question Name
- ParentSection
- Section
- Question Number
- Question Name
- Questionnaire Name

# Data Processing

In [12]:
df.isna().sum()

Questionnaire Name                           0
Account Number                               0
Account Name                                 0
Country                                      0
CDP Region                                   0
ParentSection                                0
Section                                      0
Question Number                              0
Question Name                                0
Row Number                                   0
Water security risk drivers                212
Anticipated timescale                      197
Estimated magnitude of potential impact    261
Estimated probability of impact            594
Risk description                           405
dtype: int64

Dataset contains some variables which were missing values, such as:
- Water security risk drivers
- Anticipated timescales
- Estimated magnitude of potential impact
- Estimated probability of impact
- Risk description: this variables can be delected because it were being in diffirent languages.

# Data Formatting

In [13]:
df.dtypes

Questionnaire Name                         object
Account Number                              int64
Account Name                               object
Country                                    object
CDP Region                                 object
ParentSection                              object
Section                                    object
Question Number                            object
Question Name                              object
Row Number                                  int64
Water security risk drivers                object
Anticipated timescale                      object
Estimated magnitude of potential impact    object
Estimated probability of impact            object
Risk description                           object
dtype: object